StockTrading/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tradingSystem.urls')),
]

tradingSystem/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
from . import admin_view

app_name = 'tradingSystem'

urlpatterns = [
    path('', views.goto_login, name='goto_login'),
    path('mylogin', views.mylogin, name='mylogin'),
    path('base', views.base, name='base'),
    path('register', views.register, name='register'),
    path('index', views.index, name='index'),

    # 查看上市股票，股票交易，个人股票管理,获取实时股票信息
    path('stockdetails',views.stockdetails,name='stockdetails'),
    path('stock_info/<str:stock_id>/', views.stock_info, name='stock_info'),
    path('stock_list', views.stock_list, name='stock_list'),
    path('buy_in_stock', views.buy_in_stock, name='buy_in_stock'),
    path('sold_stock',views.sold_stock,name= 'sold_stock'),
    path('get_real_quotes', views.get_real_quotes, name='get_real_quotes'),
    path('out/<str:stock_id>/', views.out, name='out'),
    path('sold_out_stock', views.sold_out_stock, name='out'),
    path('get_real_holdon', views.get_real_holdon, name='get_real_holdon'),
    #股票信息维护
    path('updateEveDayOC', views.updateEveDayOC, name='updateEveDayOC'),
    path('updateDayData', views.updateDayData, name='updateDayData'),
    path('updateTickData', views.updateTickData, name='updateTickData'),
    

    #股票评论
    path('add_stock_comment', views.add_stock_comment, name='add_stock_comment'),
    path('user_profile', views.user_profile, name='user_profile'),
    path('log_out', views.log_out, name='log_out'),
    path('do_register', views.do_register, name='do_register'),
    path('deal_user_change', views.deal_user_change, name='deal_user_change'),
    path('add_stock_comment', views.add_stock_comment, name='add_stock_comment'),

    # 管理员视图与URL
    path('a', admin_view.adm_index, name='adm_index'),
    path('a/base', admin_view.adm_base, name='adm_base'),
    path('a/user', admin_view.adm_user, name='adm_user'),
    path('a/stock', admin_view.adm_stock, name='adm_stock'),
    path('a/trading', admin_view.adm_trading, name='adm_trading'),
    path('a/news', admin_view.adm_news, name='adm_news'),
    path('a/comments', admin_view.adm_comment, name='adm_comment'),
    path('adm_view_user/<str:phone_number>', admin_view.user_detail, name='adm_view_user'),
    path('adm_view_stock/<str:stock_id>', admin_view.adm_stock_info, name='adm_view_stock'),
    # 管理员冻结用户
    path('freeze_user', admin_view.freeze_user, name='freeze_user'),
    path('unfreeze_user', admin_view.unfreeze_user, name='unfreeze_user'),
    # 管理员删除用户
    path('delete_user', admin_view.delete_user, name='delete_user'),
    # 管理员修改用户信息
    path('change_user', admin_view.change_user, name='change_user'),
    # 管理员查看新闻详情
    path('adm_news_detail/<int:news_id>', admin_view.adm_news_detail, name='adm_news_detail'),
    # 管理员编辑新闻内容
    path('adm_edit_news', admin_view.adm_edit_news, name='adm_edit_news'),
    # 管理员新建新闻
    path('adm_add_news', admin_view.adm_add_news, name='adm_add_news'),
    # 管理员调用爬虫接口获取每天新闻
    path('spy_news', admin_view.spy_news, name='spy_news'),
    # 管理员删除新闻
    path('adm_delete_news/<int:news_id>', admin_view.adm_delete_news, name='adm_delete_news'),
    # 管理员查看评论详情
    path('adm_comment_detail/<int:comment_id>', admin_view.adm_comment_detail, name='adm_comment_detail'),
    # 管理员删除评论
    path('adm_delete_comment/<int:comment_id>', admin_view.adm_delete_comment, name='adm_delete_comment'),

    # 管理员删除交易记录
    path('adm_delete_trading/<int:trading_id>', admin_view.adm_delete_trading, name='adm_delete_trading'),

    path('update_img', views.update_img, name='update_img'),

    # 查看评论
    path('comment_detail/<int:comment_id>', views.comment_detail, name='comment_detail'),

    # 为评论添加回复
    path('add_reply', views.add_reply, name='add_reply'),

    path('view_user_profile/<int:phone_number>', views.view_user_profile, name='view_user_profile'),
    # 删除评论
    path('comment_delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('comment_list', views.comment_list, name='comment_list'),

    # 新闻路由
    path('news_detail/<int:news_id>', views.news_detail, name='news_detail'),
    path('change_news', views.change_news, name='change_news'),

    #维护每日股票信息
    path('uphold', views.uphold, name='uphold'),

]

templates/adm_comment.html
{% extends "adm_base.html" %}
{% load static %}
{% load staticfiles %}

{% block title %}
管理用户评论
{% endblock %}

{% block content %}

    <section class="content-header">
        <h1>评论信息管理
            <small>管理员</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'tradingSystem:adm_index' %}"><i class="fa fa-dashboard"></i> 主页</a></li>
            <li class="active">管理员</li>
            <li class="active">评论信息管理</li>
        </ol>
    </section>
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">评论信息列表</h3>

               <div class="box-body">
                <table id="comment_table" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>评论股票</th>
                        <th>发表用户</th>
                        <th>股票名称</th>
                        <th>评论标题</th>
                        <th>评论内容</th>
                        <th>评论时间</th>
                        <th>回复次数</th>
                        <th>操作</th>
                        <th>删除</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for result in results %}
                        <tr>
                            <td><a href="{% url 'tradingSystem:stock_info' result.stock_id %}">{{ result.stock_id }}</a></td>
                            <td><a href="{% url 'tradingSystem:adm_view_user' result.phone_number %}">{{ result.phone_number }}</a></td>
                            <td>{{ result.stock_name }}</td>
                            <td>{{ result.title }}</td>
                            <td>{{ result.content }}</td>
                            <td>{{ result.comment_time | date:'Y年m月d日 H时i分' }}</td>
                            <td>{{ result.reply_nums }}</td>
                            <td style="vertical-align: middle">
                                <a href="{% url 'tradingSystem:adm_comment_detail' result.comment_id %}">详情</a>
                            </td>
                            <td style="vertical-align: middle">
                                <a style="color: red" href="{% url 'tradingSystem:adm_delete_comment' result.comment_id %}">删除</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        {% comment %}
        $.fn.dataTable.ext.search.push(
            function (settings, data, dataIndex) {
                var college = $('#college').val();
                var major = $('#major').val();
                var year = $('#year').val();
                return ((college === data[1] || college === "ALL") && (((major === data[2] || major === "ALL") && (year === data[3] || year === "ALL"))));
            }
        );
        {% endcomment %}

        $(document).ready(function () {

            var table = $('#comment_table').DataTable(
                {
                    dom: 'Bfrtip',
                    buttons: [
                        'copy',
                        {
                            extend: 'excel',
                            filename: "用户信息表",
                        },
                        {
                            extend: 'print',
                            filename: "用户信息表",
                        }
                    ],
                    "paging": true,       <!-- 允许分页 -->
                    "lengthChange": true, <!-- 允许改变每页显示的行数 -->
                    "searching": true,    <!-- 允许内容搜索 -->
                    "ordering": true,     <!-- 允许排序 -->
                    "info": true,         <!-- 显示信息 -->
                    "autoWidth": false,    <!-- 固定宽度 -->
                    "language": {
                        "sProcessing": "处理中...",
                        "sLengthMenu": "显示 _MENU_ 项结果",
                        "sZeroRecords": "没有匹配结果",
                        "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
                        "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
                        "sInfoFiltered": "(由 _MAX_ 项结果过滤)",
                        "sInfoPostFix": "",
                        "sSearch": "搜索:",
                        "sUrl": "",
                        "sEmptyTable": "表中数据为空",
                        "sLoadingRecords": "载入中...",
                        "sInfoThousands": ",",
                        "oPaginate": {
                            "sFirst": "首页",
                            "sPrevious": "上页",
                            "sNext": "下页",
                            "sLast": "末页"
                        },
                        "oAria": {
                            "sSortAscending": ": 以升序排列此列",
                            "sSortDescending": ": 以降序排列此列"
                        }
                    },
                    "columnDefs": [{
                        "searchable": false,
                        "orderable": true,
                        "targets": 0
                    }],
                    "order": [[0, 'asc']]
                }
            );

        });


    </script>
{% endblock %}

templates/adm_comment_detail.html
{% extends 'adm_base.html' %}

{% block title %}
查看评论详情
{% endblock %}

{% block content %}

<section class="content">

        <div class="row">

            <div class="col-md-12">
                <!-- Message box -->
                <div class="box box-success">
                    <div class="box-header">
                        <i class="fa fa-comments-o"></i>

                        <h3 class="box-title">{{ comment.title }}</h3>

                        <p>
                            {{ comment.content }}
                        </p>
                         <middle class="text-muted pull-right"><i
                                                class="fa fa-clock-o"></i> {{ comment.comment_time | date:'Y年m月d日 H时m分' }} </middle>


                        <div class="box-tools pull-right" data-toggle="tooltip" title="Status">
                            <div class="btn-group" data-toggle="btn-toggle">
                                <button type="button" class="btn btn-default btn-sm active"><i
                                        class="fa fa-square text-green"></i>
                                </button>
                                <button type="button" class="btn btn-default btn-sm"><i
                                        class="fa fa-square text-red"></i></button>
                            </div>
                        </div>

                    </div>

                    <div class="box-body chat" id="chat-box">
                        <!-- chat item -->
                        {% for reply  in replys %}
                            <div class="item">
                            <img src="{{ reply.user_id.photo_url }}" alt="用户头像" class="online">
                            <p class="message">
                                <b><a href="{% url 'tradingSystem:view_user_profile' reply.user_id.phone_number %}" class="name">
                                    {{ reply.user_id.user_name }}</a>
                                回复<a href="{% url 'tradingSystem:view_user_profile' reply.comment.user_id.phone_number %}" class="name">
                                    {{ reply.comment.user_id.user_name }}：
                                </a><small class="text-muted pull-right"><i class="fa fa-clock-o"></i> {{ reply.reply_time | date:'Y年m月d日 H时m分'}} </small></b>
                            {{ reply.content }}
                            </p>
                            </div>
                        {% endfor %}
                    </div>
                    <!-- /.chat -->
                    <div class="box-footer">
                        <a href="{% url 'tradingSystem:adm_delete_comment' comment.id %}"><button type="button" id="user_delete" class="btn btn-danger pull-right">删除该评论</button></a>
                    </div>
                </div>
                <!-- /.box (chat box) -->
            </div>

        </div>
        <div class="row">

        </div>

    </section>


{% endblock %}

templates/adm_news_detail.html
{% extends 'adm_base.html' %}

{% block title %}
    查看新闻详情
{% endblock %}

{% block content %}

    <section class="content">

        <div class="row">

            <div class="col-md-12">
                <!-- Message box -->
                <div class="box box-success">
                    <div class="box-header">
                        <i class="fa fa-newspaper-o"></i>

                        <h3 class="box-title">{{ news.title }}</h3>

                        <middle class="text-muted"><i
                                class="fa fa-clock-o"></i> {{ news.news_time }} </middle>

                        <div class="box-tools pull-right" data-toggle="tooltip" title="Status">
                            <div class="btn-group" data-toggle="btn-toggle">
                                <button type="button" class="btn btn-default btn-sm active"><i
                                        class="fa fa-square text-green"></i>
                                </button>
                                <button type="button" class="btn btn-default btn-sm"><i
                                        class="fa fa-square text-red"></i></button>
                            </div>
                        </div>
                    </div>

                    <div class="box-body fa-newspaper-o" id="news-box">
                        <p>
                            {{ news.content }}
                        </p>
                    </div>
                    <!-- /.chat -->
                    <div class="box-footer">
                        <button id="edit_btn" class="btn btn-success pull-left" type="button">
                            <span class="glyphicon glyphicon-pencil]">编辑新闻</span>
                        </button>
                        <a href="{% url 'tradingSystem:adm_delete_news' news.id %}"
                           class="btn btn-sm btn-danger btn-flat pull-right">删除新闻</a>
                    </div>
                </div>
                <!-- /.box (chat box) -->
            </div>

               <div class="modal fade" id="changeForm">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form action="{% url 'tradingSystem:adm_edit_news' %}"  method="post">
                        {% csrf_token %}
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">编辑新闻</h4>
                        </div>
                        <div class="modal-content" id="add_news_modal">
                            <div class="form-horizontal">

                                <div class="form-group">
                                    <label for="news_id" class="col-sm-2 control-label" style="color: red">新闻ID：</label>
                                    <div class="col-sm-10">
                                        <input type="text" id="news_id" class="form-control" readonly="readonly"
                                               name="news_id" value="{{ news.id }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="news_title" class="col-sm-2 control-label" style="color: red">新闻标题：</label>
                                    <div class="col-sm-10">
                                        <input type="text" id="news_title" class="form-control"
                                               name="news_title" value="{{ news.title }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="news_content" class="col-sm-2 control-label">新闻内容：</label>
                                    <div class="col-sm-10">
                                        <textarea name="news_content" id="news_content" class="form-control" rows="10">{{ news.content }}</textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <div class="center-block">
                                    <button id="cancelAdd" type="button" class="btn btn-default"
                                            data-dismiss="modal">取消
                                    </button>
                                    <button id="sureEdit" type="submit" class="btn btn-success">保存</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        </div>
        <div class="row">

        </div>

    </section>

{% endblock %}

{% block script %}
    <script>


        $(document).ready(function () {

           $('#edit_btn').click(function () {
               $('#changeForm').modal();
           });

        });
    </script>
{% endblock %}

templates/adm_user.html
{% extends "adm_base.html" %}
{% load static %}
{% load staticfiles %}

{% block title %}
    管理用户信息
{% endblock %}

{% block content %}

    <section class="content-header">
        <h1>全部用户信息管理
            <small>管理员</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'tradingSystem:adm_index' %}"><i class="fa fa-dashboard"></i> 主页</a></li>
            <li class="active">管理员</li>
            <li class="active">用户信息管理</li>
        </ol>
    </section>
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">用户信息列表</h3>
            <div class="box-header ">
                {% comment %}

                <label for="college" style="color: red">学院：</label><select id="college" class="select2"
                                                                           style="width: 20%">
                <option value="ALL" selected="selected">全部</option>
                {% for item in all_college %}
                    <option value="{{ item }}">{{ item }}
                {% endfor %}
            </select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <label style="color: red">专业：</label><select id="major" class="select2" style="width: 15%">
                <option value="ALL" selected="selected">全部</option>
                {% for item in all_major %}
                    <option value="{{ item }}">{{ item }}</option>
                {% endfor %}
            </select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <label>入学年份：</label><select id="year" class="select2" style="width: 15%">
                <option value="ALL" selected="selected">全部</option>
                {% for item in all_in_year %}
                    <option value="{{ item.in_year }}">{{ item.in_year }}</option>
                {% endfor %}
            </select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {% endcomment %}
            </div>

            <div class="box-body">
                <table id="user_table" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>姓名</th>
                        <th>性别</th>
                        <th>邮箱</th>
                        <th>手机号码</th>
                        <th>账户类型</th>
                        <th>身份证号</th>
                        <th>账户余额</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for user in all_user %}
                        <tr>
                            <td>{{ user.user_id }}</td>
                            <td>{{ user.user_name }}</td>
                            <td>{{ user.user_sex }}</td>
                            <td>{{ user.user_email }}</td>
                            <td>{{ user.phone_number }}</td>
                            <td>{{ user.account_type }}</td>
                            <td>{{ user.id_no }}</td>
                            <td>{{ user.account_balance }}</td>
                            <td style="vertical-align: middle">
                                <a href="{% url 'tradingSystem:adm_view_user' user.phone_number %}">详情</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        {% comment %}
        $.fn.dataTable.ext.search.push(
            function (settings, data, dataIndex) {
                var college = $('#college').val();
                var major = $('#major').val();
                var year = $('#year').val();
                return ((college === data[1] || college === "ALL") && (((major === data[2] || major === "ALL") && (year === data[3] || year === "ALL"))));
            }
        );
        {% endcomment %}

        $(document).ready(function () {
            var table = $('#user_table').DataTable(
                {
                    dom: 'Bfrtip',
                    buttons: [
                        'copy',
                        {
                            extend: 'excel',
                            filename: "用户信息表",
                        },
                        {
                            extend: 'print',
                            filename: "用户信息表",
                        }
                    ],
                    "paging": true,       <!-- 允许分页 -->
                    "lengthChange": true, <!-- 允许改变每页显示的行数 -->
                    "searching": true,    <!-- 允许内容搜索 -->
                    "ordering": true,     <!-- 允许排序 -->
                    "info": true,         <!-- 显示信息 -->
                    "autoWidth": false,    <!-- 固定宽度 -->
                    "language": {
                        "sProcessing": "处理中...",
                        "sLengthMenu": "显示 _MENU_ 项结果",
                        "sZeroRecords": "没有匹配结果",
                        "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
                        "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
                        "sInfoFiltered": "(由 _MAX_ 项结果过滤)",
                        "sInfoPostFix": "",
                        "sSearch": "搜索:",
                        "sUrl": "",
                        "sEmptyTable": "表中数据为空",
                        "sLoadingRecords": "载入中...",
                        "sInfoThousands": ",",
                        "oPaginate": {
                            "sFirst": "首页",
                            "sPrevious": "上页",
                            "sNext": "下页",
                            "sLast": "末页"
                        },
                        "oAria": {
                            "sSortAscending": ": 以升序排列此列",
                            "sSortDescending": ": 以降序排列此列"
                        }
                    },
                    "columnDefs": [{
                        "searchable": false,
                        "orderable": true,
                        "targets": 0
                    }],
                    "order": [[0, 'asc']]
                }
            );

            // Event listener to the two range filtering inputs to redraw on input
            $('#major, #year, #college').change(function () {
                table.draw();
            });
            $('.select2').select2();
        });


    </script>
{% endblock %}

templates/buy_in.html
{% extends 'mybase.html' %}

templates/comment_detail.html
{% extends 'base.html' %}

{% block title %}
查看评论详情
{% endblock %}

{% block content %}

<section class="content">

        <div class="row">

            <div class="col-md-12">
                <!-- Message box -->
                <div class="box box-success">
                    <div class="box-header">
                        <i class="fa fa-comments-o"></i>

                        <h3 class="box-title">{{ comment.title }}</h3>

                        <p>
                            {{ comment.content }}
                        </p>
                         <middle class="text-muted pull-right"><i
                                                class="fa fa-clock-o"></i> {{ comment.comment_time | date:'Y年m月d日 H时m分' }} </middle>


                        <div class="box-tools pull-right" data-toggle="tooltip" title="Status">
                            <div class="btn-group" data-toggle="btn-toggle">
                                <button type="button" class="btn btn-default btn-sm active"><i
                                        class="fa fa-square text-green"></i>
                                </button>
                                <button type="button" class="btn btn-default btn-sm"><i
                                        class="fa fa-square text-red"></i></button>
                            </div>
                        </div>

                    </div>

                    <div class="box-body chat" id="chat-box">
                        <!-- chat item -->
                        {% for reply  in replys %}
                            <div class="item">
                            <img src="{{ reply.user_id.photo_url }}" alt="用户头像" class="online">
                            <p class="message">
                                <b><a href="{% url 'tradingSystem:view_user_profile' reply.user_id.phone_number %}" class="name">
                                    {{ reply.user_id.user_name }}</a>
                                回复<a href="{% url 'tradingSystem:view_user_profile' reply.comment.user_id.phone_number %}" class="name">
                                    {{ reply.comment.user_id.user_name }}：</a>
                                <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> {{ reply.reply_time | date:'Y年m月d日 H时m分'}} </small></b>

                                {{ reply.content }}
                            </p>
                            </div>
                        {% endfor %}
                    </div>
                    <!-- /.chat -->
                    <div class="box-footer">
                        <form action="{% url 'tradingSystem:add_reply' %}" method="post">
                            {% csrf_token %}
                            <div class="input-group">
                                <input class="form-control" name="content" placeholder="输入您的评论，注意网络文明用语 ...">
                                <input type="text" hidden="hidden" name="phone_number" value="{{ user.phone_number }}">
                                <input type="text" hidden="hidden" name="comment_id" value="{{ comment.id }}">
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-success"><i class="fa fa-plus"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.box (chat box) -->
            </div>

        </div>
        <div class="row">

        </div>

    </section>


{% endblock %}